"use client";

import { motion } from "motion/react";
import { useMemo } from "react";
import { orbPalette, orbSvg, type OrbState } from "@/lib/orb";
import { cn } from "@/lib/utils";

interface AgentOrbProps {
  agentId: string;
  state: OrbState;
  size?: number;
  className?: string;
  /** disable the CSS pulse (e.g. dense tables where motion would distract) */
  still?: boolean;
  /** gentle vertical float — for the large "hero" orb in a detail view */
  float?: boolean;
}

/**
 * The signature visual. The SVG body is generated by the shared `orbSvg`
 * string generator (identical markup in the PDF); motion here handles the spring
 * on mount, the re-spring on a real state change, and an optional hero float.
 */
export function AgentOrb({
  agentId,
  state,
  size = 40,
  className,
  still = false,
  float = false,
}: AgentOrbProps) {
  const svg = useMemo(() => {
    const palette = orbPalette(agentId);
    // uid stable per agent+state so hydration matches and gradients don't collide
    const uid = `${slug(agentId)}-${state}`;
    return orbSvg({ palette, state, size, uid, animated: !still });
  }, [agentId, state, size, still]);

  return (
    <motion.span
      className={cn("inline-flex shrink-0", className)}
      style={{ width: size, height: size }}
      initial={{ scale: 0.6, opacity: 0 }}
      animate={float ? { scale: 1, opacity: 1, y: [0, -7, 0] } : { scale: 1, opacity: 1 }}
      transition={
        float
          ? { y: { duration: 4, repeat: Infinity, ease: "easeInOut" }, default: { type: "spring", stiffness: 420, damping: 26 } }
          : { type: "spring", stiffness: 420, damping: 26 }
      }
      // re-spring when the alert state toggles — communicates a real change
      key={state}
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
}

function slug(id: string): string {
  return id.replace(/[^a-zA-Z0-9]/g, "").slice(0, 12) || "orb";
}
